export const CRYPTO_OPTIONS = [
  "BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "XRPUSDT", "ADAUSDT",
  "DOGEUSDT", "AVAXUSDT", "DOTUSDT", "LINKUSDT", "MATICUSDT", "SHIBUSDT",
  "LTCUSDT", "BCHUSDT", "UNIUSDT", "ATOMUSDT", "ETCUSDT", "FILUSDT",
  "NEARUSDT", "APTUSDT", "OPUSDT", "ARBUSDT", "INJUSDT", "RNDRUSDT",
  "STXUSDT", "FTMUSDT", "SANDUSDT", "MANAUSDT", "GALAUSDT", "SUIUSDT",
  "SEIUSDT", "TIAUSDT", "PEPEUSDT", "WIFUSDT", "BONKUSDT",
  "TRXUSDT", "TONUSDT", "XLMUSDT", "MKRUSDT", "AAVEUSDT", "ALGOUSDT",
  "QNTUSDT", "VETUSDT", "ICPUSDT", "THETAUSDT", "EGLDUSDT", "AXSUSDT",
  "XTZUSDT", "EOSUSDT", "KASUSDT", "FETUSDT", "AGIXUSDT", "ROSEUSDT",
  "SNXUSDT", "IMXUSDT", "LDOUSDT", "FXSUSDT", "RUNEUSDT"
];
